Import Upstream version 6.6.3

diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -271,7 +271,7 @@ run_mayfail()
 # store the output to a variable for further processing.
 run_mayfail_stdout()
 {
-	tmp_output=$(mktemp --tmpdir btrfs-progs-test--mayfail-stdtout.XXXXXX)
+	tmp_output=$(mktemp --tmpdir btrfs-progs-mayfail-stdout.XXXXXX)
 
 	expand_command "$@"
 	echo "====== RUN MAYFAIL ${cmd_array[@]}" >> "$RESULTS" 2>&1
@@ -339,7 +339,7 @@ run_mustfail_stdout()
 	local ret
 	local tmp_output
 
-	tmp_output=$(mktemp --tmpdir btrfs-progs-test--mustfail-stdtout.XXXXXX)
+	tmp_output=$(mktemp --tmpdir btrfs-progs-mustfail-stdout.XXXXXX)
 
 	msg="$1"
 	shift
@@ -393,43 +393,66 @@ check_prereq()
 
 check_global_prereq()
 {
-	which "$1" &> /dev/null
+	type -p "$1" &> /dev/null
 	if [ $? -ne 0 ]; then
 		_fail "Failed system wide prerequisities: $1";
 	fi
 }
 
-# Check if dmsetup and targets passed as arguments are available, and skip the
-# test if they aren't
+# Check if dmsetup and the target passed as argument is available, and skip the
+# test if they aren't. Some targets may be loaded by different module name, in
+# that case the 2nd parameter is used as well if specified.
+#
+# $1: the target name, expectind module dm-$1
+# $2: optional name or alias, if specified, fail
 check_dm_target_support()
 {
+	local target="$1"
+	local secondary="$2"
+
 	setup_root_helper
 
-	which dmsetup &> /dev/null
+	type -p dmsetup &> /dev/null
 	if [ $? -ne 0 ]; then
 		_not_run "This test requires dmsetup tool";
 	fi
 
-	for target in "$@"; do
-		$SUDO_HELPER modprobe "dm-$target" >/dev/null 2>&1
-		$SUDO_HELPER dmsetup targets 2>&1 | grep -q "^$target"
-		if [ $? -ne 0 ]; then
-			_not_run "This test requires dm-$target support"
+	$SUDO_HELPER modprobe "dm-$target" >/dev/null 2>&1
+	$SUDO_HELPER dmsetup targets 2>&1 | grep -q "^$target"
+	if [ $? -ne 0 ]; then
+		# Try the other name
+		if ! [ -z "$secondary" ]; then
+			$SUDO_HELPER modprobe "dm-$secondary" >/dev/null 2>&1
+			$SUDO_HELPER dmsetup targets 2>&1 | grep -q "^$secondary"
+			if [ $? -eq 0 ]; then
+				return 0
+			fi
 		fi
-	done
+		_not_run "This test requires dm-$target support"
+	fi
 }
 
 check_image()
 {
 	local image
+	local tmp_output
+
+	tmp_output=$(mktemp --tmpdir btrfs-progs-check-image.XXXXXX)
 
 	image=$1
 	echo "testing image $(basename $image)" >> "$RESULTS"
-	"$TOP/btrfs" check "$image" >> "$RESULTS" 2>&1
-	[ $? -eq 0 ] && _fail "btrfs check should have detected corruption"
+	run_mustfail_stdout "btrfs check should have detected corruption"	\
+		"$TOP/btrfs" check "$image" &> "$tmp_output"
+
+	# Also make sure no subpage related warnings
+	check_test_results "$tmp_output" "$testname"
 
 	run_check "$TOP/btrfs" check --repair --force "$image"
-	run_check "$TOP/btrfs" check "$image"
+	run_check_stdout "$TOP/btrfs" check "$image" &> "$tmp_output"
+
+	# Also make sure no subpage related warnings for the repaired image
+	check_test_results "$tmp_output" "$testname"
+	rm -f -- "$tmp_output"
 }
 
 # Extract a usable image from packed formats
@@ -449,23 +472,23 @@ extract_image()
 		rm -f "$image.restored"
 		;;
 	*.img.xz)
-		xz --decompress --keep "$image" || \
+		xz --decompress --keep --force "$image" || \
 			_fail "failed to decompress image $image" >&2
 		image=${image%%.xz}
 		rm -f "$image.restored"
 		cleanme=$image
 		;;
 	*.raw)
-		cp --sparse=auto "$image" "$image.restored"
+		cp --sparse=auto --force "$image" "$image.restored"
 		;;
 	*.raw.xz)
-		xz --decompress --keep "$image" || \
+		xz --decompress --keep --force "$image" || \
 			_fail "failed to decompress image $image" >&2
 		image=${image%%.xz}
 		mv "$image" "$image.restored"
 		;;
 	*.stream.xz)
-		xz --decompress --keep "$image" || \
+		xz --decompress --keep --force "$image" || \
 			_fail "failed to decompress file $image" >&2
 		image=${image%%.xz}
 		mv "$image" "$image.restored"
@@ -552,6 +575,33 @@ setup_root_helper()
 	SUDO_HELPER=root_helper
 }
 
+# Check if btrfs is compiled with CONFIG_BTRFS_FS_POSIX_ACL, may need TEST_DEV.
+check_kernel_support_acl()
+{
+	if [ -f /sys/fs/btrfs/features/acl ]; then
+		if grep -q 0 /sys/fs/btrfs/features/acl; then
+			_not_run "ACL is not compiled in"
+		fi
+		return
+	fi
+
+	# It is an older kernel without acl sysfs interface.
+	if [ -f /proc/config.gz ] && \
+	   ! zgrep -q "^CONFIG_BTRFS_FS_POSIX_ACL=y" /proc/config.gz; then
+		_not_run "ACL is not compiled in"
+	fi
+
+	# If kernel is without the /proc/config.gz file.
+	run_check_mkfs_test_dev
+	run_check_mount_test_dev
+
+	if grep "$TEST_MNT" /proc/self/mounts | grep -q noacl; then
+		run_check_umount_test_dev
+		_not_run "ACL is not compiled in"
+	fi
+	run_check_umount_test_dev
+}
+
 prepare_test_dev()
 {
 	# num[K/M/G/T...]
@@ -607,6 +657,9 @@ run_check_mount_test_dev()
 		_fail "Invalid \$TEST_MNT: $TEST_MNT"
 	}
 
+	# Wait for loopdevs before mount as this could fail in the CI for some reason
+	cond_wait_for_loopdevs
+
 	run_check $SUDO_HELPER mount -t btrfs $loop_opt "$@" "$TEST_DEV" "$TEST_MNT"
 }
 
@@ -636,6 +689,9 @@ check_kernel_support()
 # compare running kernel version to the given parameter, return success
 # if running is newer than requested (let caller decide if to fail or skip)
 # $1: minimum version of running kernel in major.minor format (eg. 4.19)
+#
+# Return 0 if we meet the minimal version requirement.
+# Return 1 if not.
 check_min_kernel_version()
 {
 	local unamemajor
@@ -649,10 +705,22 @@ check_min_kernel_version()
 	uname=${uname%%-*}
 	IFS=. read unamemajor unameminor tmp <<< "$uname"
 	IFS=. read argmajor argminor tmp <<< "$1"
-	# "compare versions: ${unamemajor}.${unameminor} ? ${argmajor}.${argminor}"
-	[ "$unamemajor" -lt "$argmajor" ] || return 1
-	[ "$unameminor" -lt "$argminor" ] || return 1
-	return 0
+	# If our major > target major, we definitely meet the requirement.
+	# If our major < target major, we definitely don't meet the requirement.
+	if [ "$unamemajor" -gt "$argmajor" ]; then
+		return 0
+	fi
+	if [ "$unamemajor" -lt "$argmajor" ]; then
+		return 1
+	fi
+
+	# Only when our major is the same as the target, we need to compare
+	# the minor number.
+	# In this case, if our minor >= target minor, we meet the requirement.
+	if [ "$unameminor" -ge "$argminor" ]; then
+		return 0;
+	fi
+	return 1
 }
 
 # Get subvolume id for specified path
@@ -663,28 +731,6 @@ _get_subvolid()
 	run_check_stdout "$TOP/btrfs" inspect-internal rootid "$1" | \
 		grep -e "^[[:digit:]]\+$"
 
-}
-
-# compare running kernel version to the given parameter, return success
-# if running is newer than requested (let caller decide if to fail or skip)
-# $1: minimum version of running kernel in major.minor format (eg. 4.19)
-check_min_kernel_version()
-{
-	local unamemajor
-	local unameminor
-	local argmajor
-	local argminor
-
-	# 4.19.1-1-default
-	uname=$(uname -r)
-	# 4.19.1
-	uname=${uname%%-*}
-	IFS=. read unamemajor unameminor tmp <<< "$uname"
-	IFS=. read argmajor argminor tmp <<< "$1"
-	# "compare versions: ${unamemajor}.${unameminor} ? ${argmajor}.${argminor}"
-	[ "$unamemajor" -ge "$argmajor" ] || return 1
-	[ "$unameminor" -ge "$argminor" ] || return 1
-	return 0
 }
 
 # how many files to create.
@@ -800,6 +846,7 @@ prepare_loopdevs()
 		chmod a+rw "$loopdev_prefix$i"
 		truncate -s0 "$loopdev_prefix$i"
 		truncate -s2g "$loopdev_prefix$i"
+		run_check sync "$loopdev_prefix$i"
 		loopdevs[$i]=`run_check_stdout $SUDO_HELPER losetup --find --show "$loopdev_prefix$i"`
 	done
 }
@@ -817,6 +864,22 @@ cleanup_loopdevs()
 	run_check $SUDO_HELPER losetup --all
 }
 
+# Loop devices may not be ready for mount after mkfs (observed in the CI), wait
+# for them explicitly. Errors are reported but tolerated, the mount could succeed
+# eventually or the whole test will fail anyway.
+wait_for_loopdevs()
+{
+	for dev in ${loopdevs[@]}; do
+		run_mayfail $SUDO_HELPER "$TOP/btrfs" device ready "$dev"
+	done
+}
+
+cond_wait_for_loopdevs() {
+	if [ -n "${loopdevs[1]}" ]; then
+		wait_for_loopdevs
+	fi
+}
+
 init_env()
 {
 	TEST_MNT="${TEST_MNT:-$TEST_TOP/mnt}"
@@ -832,4 +895,58 @@ init_env()
 		echo "  convert: $TEST_ARGS_CONVERT" >> "$RESULTS"
 	fi
 }
+
+# Catch critical warning messages in test results
+check_test_results()
+{
+	local results="$1"
+	local testname="$2"
+
+	# Check subpage related warning
+	if grep -q "not nodesize aligned" "$results"; then
+		_fail "found subpage related warning for case $testname"
+	fi
+}
+
+# Create at temporary file in $TMPDIR
+# $1: optional identifier that'll be part of the name
+_mktemp() {
+	local tmp
+	local name
+
+	name="btrfs-progs${1:+-$1}.XXXXXX"
+	_log "Create temporary file $name"
+	tmp=$(mktemp --tmpdir "$name")
+	echo -n "$tmp"
+}
+
+# Create at temporary directory in $TMPDIR
+# $1: optional identifier that'll be part of the name
+_mktemp_dir() {
+	local tmp
+	local name
+
+	name="btrfs-progs${1:+-$1}.XXXXXX"
+	_log "Create temporary file $name"
+	tmp=$(mktemp -d --tmpdir "$name")
+	echo -n "$tmp"
+}
+
+# Create temporary file of the given name in the local test directory (eg. when
+# it's a large image and not suitable for /tmp), this also supports NFS where
+# the file needs to be created by regular user and made available for roo
+# $1: file name
+# $2: optional size (argument suitable for truncate)
+_mktemp_local() {
+	local name
+	local size
+
+	name="$1"
+	size="${2:-0}"
+	_log "Create local temporary file $name"
+	rm -f -- "$name"
+	run_check truncate -s "$size" -- "$name"
+	run_check chmod a+w -- "$name"
+}
+
 init_env
